apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

patchesStrategicMerge:
- custom-env.yaml

resources:
- ../../base
secretGenerator:
- literals:
  - db-password=teste123
  name: test-ppro
  type: Opaque
